"""Reference / tag data loading (Phase 1F).

Loads the small business-managed lookup tables that are, in current
production, Excel `Table` (ListObject) objects living in the same
workbook as the Power Query queries -- `tbl_Tag_Region`, `tbl_Tag_Top60`,
`tbl_tag_sourceplant`, `rec_req_type`, `plant_evaluation`
(see docs/nin_data_contracts.md section 6 and the `Excel.CurrentWorkbook()`
references in `docs/powerquery_m/`) -- so
`nin_pipeline.sources.prdpl3.enrich_prdpl3` and
`nin_pipeline.sources.mrp_elements_rec.enrich_mrp_elements_rec` can be
called with plain DataFrames as they already expect.

Note: `Table_BOBL` is *not* loaded here. Unlike the other five tables,
BOBL is not business-user-maintained tag data -- it is pulled from a
separate PowerBI export -- and BOBL processing is deferred for now (see
docs/nin_data_contracts.md Open Decision #10). `nin_pipeline.sources.bobl`
still has the transformation logic ready for when its real input source
is decided.

Because these tables are maintained directly by business users in Excel
(not regenerated by an automated extract), two loading paths are
supported so users can keep editing them exactly as they do today:

1. `load_reference_data_from_workbook(path)` -- reads the named Excel
   Tables **directly** out of a single `.xlsx` workbook (via `openpyxl`),
   matching each table by its Excel Table name (case-insensitively,
   regardless of which worksheet it lives on). This is the recommended
   option: no copy/paste/export step is needed -- point the pipeline at
   the same workbook the tables are edited in and re-run.
2. `load_reference_data(folder)` -- reads one CSV per table from a
   `reference_data_folder`, for cases where a workbook isn't available or
   an automated CSV export of these tables already exists.

Expected CSV file names under `reference_data_folder` (one CSV per table,
column names matching the corresponding `.pq` source exactly):

- `region.csv` -- columns: Plant, Region
- `top60.csv` -- columns: plant_material_key, plant, material, top_60_flag
- `sourceplant.csv` -- columns: source_key, desc, source_plant
- `rec_req_type.csv` -- columns: type, negative (also accepts `negative?`,
  any casing; extra columns such as `description` are tolerated and
  passed through unused). Values accept "true"/"false", "1"/"0", or
  "yes"/"no", case-insensitive; any other/blank value is treated as
  not-negative, matching the default in `enrich_mrp_elements_rec`)
- `plant_evaluation.csv` -- columns: Plant (single active-plant row)

`active_plant(reference_data)` returns that single plant. For running the
pipeline across *every* plant in scope instead, see `load_active_plants()`
below, which reads a separate, operationally-maintained multi-plant list
(not one of the five Excel Tables above -- see
docs/nin_data_contracts.md Open Decision #11).

The Excel Table names looked up by `load_reference_data_from_workbook`
mirror the CSV keys above 1:1 (see `EXCEL_TABLE_NAMES`).
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pandas as pd

TRUE_VALUES = {"true", "1", "yes"}

# Real Excel Table (ListObject) names referenced by `Excel.CurrentWorkbook()`
# across docs/powerquery_m/ -- confirmed against stg_prdpl3_enriched.pq,
# stg_mm_mrp_elements_rec_enriched.pq/_clean.pq, and tags/tbl_tag_*.pq.
# (`Table_BOBL` is intentionally excluded -- see module docstring.)
EXCEL_TABLE_NAMES = {
    "region": "tbl_Tag_Region",
    "top60": "tbl_Tag_Top60",
    "sourceplant": "tbl_tag_sourceplant",
    "rec_req_type": "rec_req_type",
    "plant_evaluation": "plant_evaluation",
}


@dataclass
class ReferenceData:
    region: pd.DataFrame
    top60: pd.DataFrame
    sourceplant: pd.DataFrame
    rec_req_type: pd.DataFrame
    plant_evaluation: pd.DataFrame


def _coerce_rec_req_type(df: pd.DataFrame) -> pd.DataFrame:
    """Normalize the `rec_req_type` table's negative-flag column and
    coerce it to a proper boolean.

    Tolerates minor header variations business users may introduce when
    editing this table directly (e.g. `negative?` instead of `negative`,
    any casing) -- matched case-insensitively, trailing `?`/whitespace
    stripped, then renamed to the canonical `negative` name expected by
    `nin_pipeline.sources.mrp_elements_rec.enrich_mrp_elements_rec`. Any
    other extra columns (e.g. a human-readable `description` column) are
    passed through unchanged.
    """
    df = df.copy()
    if "negative" not in df.columns:
        for col in df.columns:
            if col.strip().rstrip("?").strip().lower() == "negative":
                df = df.rename(columns={col: "negative"})
                break
    if "negative" not in df.columns:
        raise KeyError(
            "rec_req_type table must have a 'negative' (or 'negative?') column."
        )
    df["negative"] = (
        df["negative"].astype("string").str.strip().str.lower().isin(TRUE_VALUES)
    )
    return df


def _read_csv(folder: Path, filename: str) -> pd.DataFrame:
    path = folder / filename
    if not path.exists():
        raise FileNotFoundError(f"Reference data file not found: {path}")
    return pd.read_csv(path, dtype="string")


def load_reference_data(folder: str | Path) -> ReferenceData:
    """Load all reference/tag tables from a folder of CSVs (see module
    docstring for expected file names and columns)."""
    folder = Path(folder)

    return ReferenceData(
        region=_read_csv(folder, "region.csv"),
        top60=_read_csv(folder, "top60.csv"),
        sourceplant=_read_csv(folder, "sourceplant.csv"),
        rec_req_type=_coerce_rec_req_type(_read_csv(folder, "rec_req_type.csv")),
        plant_evaluation=_read_csv(folder, "plant_evaluation.csv"),
    )


def _read_excel_table(wb, table_name: str) -> pd.DataFrame:
    """Locate a named Excel Table (ListObject) by name, case-insensitively,
    across every worksheet in an already-opened `openpyxl` workbook, and
    return its data (header row + data rows) as a string-typed DataFrame."""
    target = table_name.strip().lower()
    for worksheet in wb.worksheets:
        for table in worksheet.tables.values():
            if table.name.strip().lower() != target:
                continue
            rows = list(worksheet[table.ref])
            header = [
                str(cell.value) if cell.value is not None else "" for cell in rows[0]
            ]
            data = [[cell.value for cell in row] for row in rows[1:]]
            return pd.DataFrame(data, columns=header).astype("string")
    raise ValueError(f"Excel table '{table_name}' not found in workbook.")


def load_reference_data_from_workbook(path: str | Path) -> ReferenceData:
    """Load all reference/tag tables directly from the named Excel Tables
    in a single `.xlsx` workbook -- the recommended option, since it lets
    business users keep maintaining these tables in Excel exactly as they
    do today, with no manual CSV export step. See `EXCEL_TABLE_NAMES` for
    the exact table names looked up (matched case-insensitively)."""
    import openpyxl

    wb = openpyxl.load_workbook(path, data_only=True, read_only=False)
    tables = {
        key: _read_excel_table(wb, name) for key, name in EXCEL_TABLE_NAMES.items()
    }
    tables["rec_req_type"] = _coerce_rec_req_type(tables["rec_req_type"])
    return ReferenceData(**tables)


def active_plant(reference_data: ReferenceData) -> str:
    """Return the single active evaluation plant, matching the
    `ParamPlant` step used identically by every `stg_<source>_clean.pq`."""
    df = reference_data.plant_evaluation
    if len(df) == 0:
        raise ValueError("plant_evaluation table must contain one plant row.")
    return str(df.iloc[0]["Plant"]).strip().upper()


def load_active_plants(path: str | Path) -> list[str]:
    """Load a multi-plant run list from a headerless, single-column CSV
    (one plant code per row -- e.g. the file dropped in
    `\\\\filer3\\power_bi$\\GSP\\Stockout_Excel\\Input`), for running the
    pipeline across every plant in scope rather than the single plant in
    `plant_evaluation.csv`.

    Blank rows are skipped; codes are trimmed and upper-cased; duplicates
    are dropped while preserving first-seen order.
    """
    df = pd.read_csv(path, header=None, dtype="string")
    codes = df[0].astype("string").str.strip().str.upper()
    codes = codes[codes.notna() & (codes != "")]
    return list(dict.fromkeys(codes))
