#!/usr/bin/env python3
"""Record snapshot metadata for an existing run directory.

Usage:
  python scripts/record_snapshot.py --run-id 20260804_143223

Scans runs/<run_id>/raw and test_data/expected, records absolute paths in the run manifest,
counts rows for CSV/TXT files, and writes the updated manifest.json.
"""
import argparse
import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / 'runs'
TEST_RAW = ROOT / 'test_data' / 'raw'
TEST_EXPECTED = ROOT / 'test_data' / 'expected'


def count_csv_rows(path: Path):
    try:
        with path.open('r', errors='ignore') as fh:
            return sum(1 for _ in fh)
    except OSError:
        return None


def scan_run(run_id: str):
    run_dir = RUNS / run_id
    raw_dir = run_dir / 'raw'
    manifest_path = run_dir / 'manifest.json'
    if not run_dir.exists():
        raise SystemExit(f'Run directory not found: {run_dir}')
    if not manifest_path.exists():
        # create a basic manifest if missing
        manifest = {
            'run_id': run_id,
            'started_at': None,
            'created_by': os.getenv('USER') or os.getenv('USERNAME') or 'unknown',
            'status': 'pending',
            'as_of_date': None,
            'sources': {},
            'row_counts': {},
            'notes': 'Generated by scripts/record_snapshot.py'
        }
    else:
        manifest = json.loads(manifest_path.read_text())

    # discover raw files in run/raw
    sources = {}
    row_counts = {}
    if raw_dir.exists():
        for p in sorted(raw_dir.iterdir()):
            if p.is_file():
                name = p.name
                sources[name] = str(p.resolve())
                if p.suffix.lower() in ('.csv', '.txt'):
                    row = count_csv_rows(p)
                    row_counts[name] = row
                else:
                    row_counts[name] = None

    # discover expected files (powerquery output) in test_data/expected
    expected_files = {}
    if TEST_EXPECTED.exists():
        for p in sorted(TEST_EXPECTED.iterdir()):
            if p.is_file():
                expected_files[p.name] = str(p.resolve())

    # attempt to map known sources by substring
    mapped = {
        'prdpl3': None,
        'mrp_rec': None,
        'mrp_doh': None,
        'mb5t': None,
        'powerquery_output': None
    }
    for fname, path in sources.items():
        low = fname.lower()
        if 'prdpl3' in low or 'prdpl' in low:
            mapped['prdpl3'] = path
        elif 'mrp_rec' in low or 'mrprec' in low or 'mrp_rec' in low:
            mapped['mrp_rec'] = path
        elif 'mrp_doh' in low or 'mrpdoh' in low or 'doh' in low:
            mapped['mrp_doh'] = path
        elif 'mb5t' in low:
            mapped['mb5t'] = path
    # map powerquery if only one expected file exists
    if len(expected_files) == 1:
        mapped['powerquery_output'] = next(iter(expected_files.values()))
    elif 'powerquery' in ' '.join(expected_files.keys()).lower():
        for k,v in expected_files.items():
            if 'powerquery' in k.lower():
                mapped['powerquery_output'] = v

    manifest['sources'] = mapped
    # convert row_counts dict to group-level keys
    grouped_counts = {}
    for fname, cnt in row_counts.items():
        # assign to matching group if possible
        low = fname.lower()
        if 'prdpl3' in low:
            grouped_counts['prdpl3_raw'] = cnt
        elif 'mrp_rec' in low or 'mrprec' in low:
            grouped_counts['mrp_rec_raw'] = cnt
        elif 'mrp_doh' in low or 'mrpdoh' in low or 'doh' in low:
            grouped_counts['mrp_doh_raw'] = cnt
        elif 'mb5t' in low:
            grouped_counts['mb5t_raw'] = cnt
        else:
            grouped_counts[fname] = cnt

    # merge into manifest
    manifest['row_counts'] = manifest.get('row_counts', {})
    manifest['row_counts'].update(grouped_counts)
    manifest['status'] = 'completed'

    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f'Updated manifest: {manifest_path}')
    print('Sources recorded:')
    for k,v in manifest['sources'].items():
        print(f'  {k}: {v}')
    print('Row counts:')
    for k,v in manifest['row_counts'].items():
        print(f'  {k}: {v}')


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--run-id', required=True)
    args = p.parse_args()
    scan_run(args.run_id)
